### ISSUE TITLE
Unable to configure/build.

### ISSUE THREAD

**Issue by spacegonzo** [superzerg/logic-analyzer#1]
When I try to configure logic-analyzer "./configure", this error message is returned :
"configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../..""

It looks like there are 4 non-local links in the repository :

depcomp -> /usr/share/automake-1.11/depcomp
INSTALL -> /usr/share/automake-1.11/INSTALL
install-sh -> /usr/share/automake-1.11/install-sh
missing -> /usr/share/automake-1.11/missing

**Comment by superzerg** [comment]
Did you try to install autoconf and automake ?
