### ISSUE TITLE
Unable to launch the ./configure

### ISSUE THREAD

**Issue by louckas** [superzerg/logic-analyzer#2]
Hello, 

I know it's an old project, but it look very nice and corresponding to what I need.
I have the same problem as spacegonzo, when i try to to launch the ./configure : "configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."".

I tried to install the autoconf and automake package without success. I try to use your project on a raspberry pi 3b with a raspbian os.

Best regards.

**Comment by superzerg** [comment]
I could not reproduce the problem.
I will try with a fresh raspbian tomorrow.

**Comment by louckas** [comment]
we found a way to get ride of this problem, you just need to remove the 4 file (INSTALL install.sh ...) and you can launch an autoconf then the configure. But after that we have a problem with the mathgl library, its not possible to get it as a package anymore (not the version 1), and when we try with with and old version we had problem to make the library and then after that their is a problem with you code and the library. The make told us that he can't found the SetTick in graphgl object.

**Comment by superzerg** [comment]
It seems the pakage libmgl-dev does not contain the v1 files anymore.
I remved the problematic files from the repo and I updated the README.md file with instructions.
The updated instructions worked for me on a fresh raspbian-lite install.
Is it working for you ? If so I'll close the bug.

**Comment by louckas** [comment]
Work great now, thanks you for your work and for helping me 4 years after.
